feat: improve logging for detect command
tofuutils/tenv pull request #165
Opened 2024-06-12 13:34 UTC by kvendingoldo

2024-06-12 13:59 UTC, kvendingoldo commented
related to https://github.com/tofuutils/tenv/issues/163

2024-06-13 19:30 UTC, kvendingoldo commented
@dvaumoron any comments ? :)

2024-06-13 20:14 UTC, dvaumoron requested changes

2024-06-13 20:14 UTC, dvaumoron commented on versionmanager/manager.go
>  			m.conf.Displayer.Flush(proxyCall)
This line is no longer needed

2024-06-13 20:14 UTC, dvaumoron commented on versionmanager/manager.go
> +			m.conf.Displayer.Display("Auto-install is disabled. To install " + version + " version you can set environment variable TENV_AUTO_INSTALL=true, or install it via any of the following command: 'ten
You should use `loghelper.Concat`, instead of multiple `+` (more efficient as it use a `strings.Builder`)

2024-06-13 20:17 UTC, dvaumoron requested changes

2024-06-13 20:17 UTC, dvaumoron commented on versionmanager/manager.go
>  			m.conf.Displayer.Flush(proxyCall)
This line is not needed here anymore, however it should be called before `return "", errNoCompatibleLocally`

2024-06-14 09:22 UTC, kvendingoldo commented
Updated

2024-06-16 11:58 UTC, dvaumoron approved these changes
LGTM

2024-06-16 15:41 UTC, merged